### ISSUE TITLE
Help editor 

### ISSUE THREAD

**Issue by nimdanor** [PremierLangage/Yggdrasil#37]
dans l'exo suivant je n'arrive pas a faire fonctionner l'editeur
Yggdrasil/conceptexo/ComputerScience/python/concept/function/carre.pl

**Comment by mciissee** [comment]
C'est un bug au niveau de l'exercice.

Dans le fichier Yggdrasil/conceptexo/ComputerScience/python/template/pltest.pl remplacez la ligne 
`53: editor.fontsize=14px`
par
`editor.fontsize=14`

**Comment by nimdanor** [comment]
Merci
