### ISSUE TITLE
AIDE POUR ÉCRIRE UNE DEMANDE

### ISSUE THREAD

**Issue by nborie** [PremierLangage/Yggdrasil#46]
Pour simplifier l’écriture des demandes il suffit d'utiliser le formulaire suivant 

https://docs.google.com/forms/d/e/1FAIpQLScOJERvXy82d0OQamqqi7Qh5NiCW1XidzQ04dMvrxIRRx7_JA/viewform?usp=pp_url 

**Si vous avez un compte github** Utiliser @votrepseudogithub comme valeur pour le courrier électronique merci

La validation du formulaire créer une demande avec un lien sur un fichier google doc contenant une version longue de votre demande.

**Comment by qcoumes** [comment]
Pourquoi ne pas créer un template ?

**Comment by qcoumes** [comment]
Il semblerait que seul les admins puissent en créer un. C'est dans Insight > Community > Issue templates

**Comment by nimdanor** [comment]
deux choses 
- je ne suis pas arriver à ecrire un template valable pour notre besoin.
- j'ai envoyer à Nicolas un script ou il faut changer le modèle d'issue

**Comment by nimdanor** [comment]
Si vous n'accedez pas a un exercice sur pl.u-pem.fr il faut préalablement vous connecter 
par le   https://elearning.u-pem.fr de l'UPEM avec le couple d'identifiants suivant 
EssoxLucius1 / EssoxLucius1
Puis vous connecter avec un des liens LTI.
