### ISSUE TITLE
[Physique] Détermination de constantes d’intégration pour un oscillateur

### ISSUE THREAD

**Issue by RichardTaillet** [PremierLangage/Yggdrasil#64]
**Titre de l'exercice :**

Détermination de constantes d’intégration pour un oscillateur

**Public visé :**

L1 de physique

**Contexte d’utilisation :**

Entraînement et évaluation

**Objectif pédagogique :**

Savoir déterminer une constante d’intégration dans la solution d’une équation différentielle du second ordre, à partir des conditions initiales

**TAGS :**

mécanique, équations différentielles

**Description de l'exercice (Texte) :**

Entre crochets : indications pour la personne qui programme.

## Énoncé :

On s’intéresse au mouvement d’un oscillateur amorti le long d’un axe $x$. On peut montrer, en appliquant le principe fondamental de la dynamique, que la position $x(t)$ est décrite par l’équation suivante : [3 cas possibles]

### [cas 1]
\[
x(t) = \left[ A \cos(\omega t) + B\sin (\omega t)\right]\, e^{-\gamma_1 t}
\]
Avec $\omega = $ [valeur numérique entière comprise entre 1 et 100] $\,\text{rad/s}$ et $\gamma_1 =$ [valeur numérique entière comprise entre 0 et 10] $\;\text{s}^{-1}$.

### [cas 2]
\[
x(t) = \left[ A + B\, t \right]\, e^{-\gamma_1 t}
\]
Avec $\gamma_1 =$ [valeur numérique entière comprise entre 0 et 10] $\;\text{s}^{-1}$.

### [cas 3]
\[
x(t) =A\, e^{-\gamma_1 t}+ B\, e^{-\gamma_2 t}
\]
Avec $\gamma_1 =$ [valeur numérique entière comprise entre 0 et 10] $\;\text{s}^{-1}$ et $\gamma_2 =$ [valeur numérique entière comprise entre 0 et 10 différente de gamma_1] $\;\text{s}^{-1}$.

Sachant que la position initiale est $x(0)=$ [valeur aléatoire entière X entre -10 et 10] $\,\text{m}$ et que la vitesse initiale est $v(0) =$ [valeur aléatoire entière V entre -10 et 10] $\,\text{m/s}$, déterminer la valeur des constantes A et B avec 3 chiffres significatifs, en précisant les unités.

### [cas 1] 
A = X [unité : m]
B = (X*gamma1 + V)/omega [unité : m]

### [cas 2}
A = X [unité : m]
B = V + A * gamma1 [unité : m/s]

### [cas 3]
B = (V+ X *gamma1)(gamma1-gamma2) [unité : m]
A = X-B = X - (V+ X *gamma1)(gamma1-gamma2) [unité : m]

**Champs de saisie :**

A et B, deux valeurs numériques float avec unités et nombre de chiffres significatifs.

**Valeurs aléatoires et algorithme qui les génère :**

1 tir aléatoire du cas choisi (1, 2 ou 3) puis, dans chaque cas, 2 valeurs aléatoires entières (cf l’énoncé ci-dessus)

**Comment détermine-t-on si la réponse est juste :**

Comparaison de la valeur numérique et de l’unité de la réponse à la réponse calculée correctement (cf solution ci-dessus). Vérifier le nombre de chiffres significatifs.

**Feedback à l'étudiant :**

Indiquer si la valeur et/ou l’unité sont incorrects, indiquer si la précision fournie n’est pas adaptée.

**Comment by esandier** [comment]
Merci de passer par le formulaire pour qu'un document partagé soit créé, plus adapté aux échanges, et important pour nos archives. Cela créera aussi une nouvelle "issue" sur github. Il suffira de copier-coller celle-ci dans le document partagé et la nouvelle "issue". Je marque celle-ci comme fermée.

**Comment by RichardTaillet** [comment]
Bonjour,

La première chose que nous avons faite ce matin, c’est de demander à Damir où trouver ce formulaire. Sans réponse, la seconde a été de chercher le formulaire, nous ne l’avons pas trouvé (ni dans nos mails, ni sur github). Pouvez-vous nous indiquer où trouver ce formulaire, ou mieux, où se trouve l’information de la localisation de ce formulaire ?

Du coup, il serait probablement judicieux d’effacer le message intitulé « AIDE POUR ECRIRE UNE DEMANDE » dans les « issues » du github, qui nous avait semblé contenir la procédure correcte.

Merci !

Richard et Gilles.

**Comment by esandier** [comment]
Pas de souci, nous avons fait ça un peu dans la précipitation! Voici le lien vers le formulaire:
https://docs.google.com/forms/d/e/1FAIpQLScOJERvXy82d0OQamqqi7Qh5NiCW1XidzQ04dMvrxIRRx7_JA/viewform?usp=pp_url

après validation du formulaire, vous recevrez deux liens: vers le document partagé et vers GitHub. Comme je l'ai dit, inutile de remplir tout le formulaire, juste  les champs obligatoires, ensuite vous pouvez copier-coller ce que vous avez déjà fait dans le document partagé, et dans la nouvelle issue.
bon travail!
Etienne
    Le lundi 1 juillet 2019 à 16:36:42 UTC+2, RichardTaillet <notifications@github.com> a écrit :  
 
 Bonjour,

La première chose que nous avons faite ce matin, c’est de demander à Damir où trouver ce formulaire. Sans réponse, la seconde a été de chercher le formulaire, nous ne l’avons pas trouvé (ni dans nos mails, ni sur github). Pouvez-vous nous indiquer où trouver ce formulaire, ou mieux, où se trouve l’information de la localisation de ce formulaire ?

Du coup, il serait probablement judicieux d’effacer le message intitulé « AIDE POUR ECRIRE UNE DEMANDE » dans les « issues » du github, qui nous avait semblé contenir la procédure correcte.

Merci !

Richard et Gilles.

**Comment by RichardTaillet** [comment]
Super, merci pour ces précisions !! :)
