### ISSUE TITLE
Problems in dynaloopgrader

### ISSUE THREAD

**Issue by nimdanor** [PremierLangage/Yggdrasil#76]
The following line are wrong in for three differentes reasons 👎 
1) you don't check that taboo or needed are defined in the pl
2) the way you check a taboo is bad if there is a comment in the student file saying i don't use a "for"  you say it's wrong but that's false because the sudtend dosn't use for 
3) is the worst you just kill the processus making an exercice error of a wrong answer from the student you must give the student a feedback in this case.

    if dic['taboo'] in student:
        print("Don't use '{}' loop for this exercise ".format(dic['taboo']), file = sys.stderr)
        sys.exit(1)

    if dic['needed'] not in student:
        print("Use '{}' loop for this exercise ".format(dic['needed']), file = sys.stderr)
        sys.exit(1)

**Comment by nimdanor** [comment]
En d'autre termes 
1) il faut verifier l'existance des balises que l'on utilise 
if 'taboo' in dic : 
   if checktaboo(dic['taboo']) : 
         output(0," there is a taboo on the use of "+dic['taboo'])
         sys.exit(1)

**Comment by nimdanor** [comment]
la fonction checktaboo(taboos, student) peut en première approche éliminer les commentaires dans student puis pour tout les string dans taboos tester la présence.

**Comment by varlorosita** [comment]
Les problèmes liés au loop grader ont été corrigés. Voici le lien pour que vous puissiez vérifier : 
https://github.com/PremierLangage/Yggdrasil/tree/master/ComputerScience/python/.attic/python/Reprise_Boris/encours/loop

**Comment by nimdanor** [comment]
cleaning
