### ISSUE TITLE
template/dragdrop.pl

### ISSUE THREAD

**Issue by nimdanor** [PremierLangage/Yggdrasil#80]
@ddoyen is this one of yours ? 
Should sign your code !
the demo is not working ? 
should we remove it and change it to a componant ?

**Comment by ddoyen** [comment]
Yes, I am the author of most pl files in template/. They are now obsolete with the components and can be removed.

**Comment by nimdanor** [comment]
Could you do some deleting of your unused files please.
And could you use the author tag.

**Comment by ddoyen** [comment]
I've cleaned the directory.
