### ISSUE TITLE
Liste des multiples

### ISSUE THREAD

**Issue by ebrunach** [PremierLangage/Yggdrasil#85]
La solution suivante ne fonctionne pas.
```n=int(input()) 
if n>0:
  for i in range(n):
    print(17*i,end="")
```
Le message d'erreur est le suivant (test 2 OK et 1 et 2 failure):
Attendu:

    017

Obtenu:

    017

Attendu:
Expected:

Got nothing

Obtenu:

Attendu:

    01734516885102119136153170187204221238255272289306323340357374391408425442459476493510527544561578595612629646663680697714731748765782799816833850867884901918935952969986100310201037105410711088110511221139115611731190120712241241125812751292130913261343136013771394141114281445146214791496151315301547156415811598161516321649166616831700171717341751176817851802181918361853

Obtenu:

    01734516885102119136153170187204221238255272289306323340357374391408425442459476493510527544561578595612629646663680697714731748765782799816833850867884901918935952969986100310201037105410711088110511221139115611731190120712241241125812751292130913261343136013771394141114281445146214791496151315301547156415811598161516321649166616831700171717341751176817851802181918361853

**Comment by nimdanor** [comment]
Il doit manquer un passage a la ligne.

**Comment by ebrunach** [comment]
Dans la réponse ou dans la vérification ? Je veux bien modifier la source
pour éviter ce genre de faux négatif mais je ne la source de cet exercice.

Le jeu. 10 oct. 2019 à 13:05, Dominique Revuz <notifications@github.com> a
écrit :

**Comment by nimdanor** [comment]
n=int(input())
if n>=0:
  for i in range(n):
    print(17*i,end="")
  print()

ou bien 
n=int(input())
if not n<0:
    s=""
    for i in range(n):
         s+=str(i*17)
    print(s)
