### ISSUE TITLE
Boucle d'OR

### ISSUE THREAD

**Issue by ebrunach** [PremierLangage/Yggdrasil#86]
Voici l 'énoncé:

> Lire un entier sur l'entré dans la variable X.
> X est toujours positif.
> Affichez les entiers de -39 à -39+X parcourus de 5 en 5 qui sont divisibles par 7
> et calculez le caré de leur produit .
> seed=65

Quel est ce seed?

Voici ma réponse, il me semble qu'elle répond à l'énoncé, mais ne correspond pas au résultat attendu et ne prend pas en compte ce "seed"

```
X=int(input())
if X>0:
    a=-39
    sum=0
    while(a<=-39+X):
        if(a%7==0):
            print(a)
            sum=sum*a
        a=a+5
    print(sum**2)

**Comment by nimdanor** [comment]
Votre produit est nul s=0
Cela ne peut fonctionner

Sinon la seed c'est pour être capable de rejourer l'exercice.

**Comment by ebrunach** [comment]
Pas faux.

Il est dommage d'afficher seed si cela ne sert à rien pour l'étudiant.
C'est plutôt perturbant.

Il n'empêche que les résultats attendus affichés sont bien étrange.




Le jeu. 10 oct. 2019 à 15:14, Dominique Revuz <notifications@github.com> a
écrit :
