### ISSUE TITLE
Parser Gift/Cloze/etc.

### ISSUE THREAD

**Issue by ddoyen** [PremierLangage/Yggdrasil#91]
@nborie @mciissee @steph-sanches 

Est-ce que vous avez déjà codé un parser Gift/Cloze (ou format du même genre) ?

Je commence à bricoler un builder et un grader pour des exercices multistep. Pour l'instant je génère les questions dans le before mais j'aimerais ajouter la possibilité de lire les questions à partir d'un fichier externe dans un format texte.

**Comment by mciissee** [comment]
Voici le [lien direct](https://github.com/PremierLangage/premierlangage/blob/master/apps/loader/parsers/gift.py) pour le parser gift. Le parser est interne au serveur PL. Il n'est donc pas utilisable sur la sandbox. Le parser (comme tous les parseurs du serveur, PL, PLTP...) sont accessible via une API mais comme la sandbox ne peut pas accéder à internet c'est donc impossible.

Pour le parseur cloze, je pense que @steph-sanches a ou est entrai de faire une version en local. Mais je pense que comme cloze c'est du xml il existe forcément un parseur xml dans la lib standard de python

**Comment by ddoyen** [comment]
Merci @mciissee

**Comment by nimdanor** [comment]
Ouais et bien le parseur gift me pose des problème en effet au lieux. de  bien décompose les gift en. une structure de question il laisse le before et evaluator faire la moitie du travail. Ce qui fait qu'il faut connaitre la syntaxe gift pour utiliser les exercice de type gift alors qu'ils sont classiques et que l'on peut proposer des syntaxes plus simples en PL.

**Comment by nimdanor** [comment]
Cleaning
